[package]
name = "cosmobots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
rand = "0.8"
rand_pcg = "0.3.1"
noise = "0.8.0"
lazy_static = "1.4.0"
